version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run linting
          command: yarn lint

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests
          command: yarn test

  build_and_deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '94:3a:36:a7:42:98:fd:ee:f0:27:4a:6e:06:e0:f3:ec'
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Build and deploy to gh-pages
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME

            yarn deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint:
          filters:
            branches:
              ignore: gh-pages
      - test:
          requires:
            - lint
          filters:
            branches:
              ignore: gh-pages
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              only: main
